### ISSUE TITLE
bbq.domain.Repository._createEntity

### ISSUE THREAD

**Issue by alanshaw** [achingbrain/bbq#13]
I'm having trouble understanding the loop at the end of this method:

```
if(this._entities[i].equals(data))
```

If the stored entity at index "i" equals data then...

```
data = this.get(i);
```

Set data equal to the entity in the repository

```
data.processData(data.options.data);
```

Get the entity to process the data it already has...

So, basically it throws away the new version of the entity - in my case it uses the partially loaded entity over the JSON I pass to Repository.add.

Could you explain, or is this a bug?

**Comment by achingbrain** [comment]
This is on purpose but you've also uncovered a bug.  The idea is that if you use a setter on an Entity, it updates any propertyDisplays to reflect the change in value.  If you've got two versions of the same entity, you'd have to call the setter on both of them.  Repository ensures that you are only ever dealing with one copy of an Entity.

The bug though is that the data from the incoming Entity should be applied to the the original Entity, rather than re-applying the original Entity data.  I've fixed this, added a test and will deploy a new snapshot.

**Comment by alanshaw** [comment]
Great, thank you

**Comment by achingbrain** [comment]
Snapshot deployed, should be available in the next 10 mins or so.
